name: Status Badge

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  badge:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Status Badge
        uses: actions/github-script@v7
        with:
          script: |
            const { context } = github;
            const { owner, repo } = context.repo;
            
            // Get the latest workflow run
            const workflowRuns = await github.rest.actions.listWorkflowRuns({
              owner,
              repo,
              workflow_id: 'ci.yml',
              branch: 'main',
              per_page: 1
            });
            
            const latestRun = workflowRuns.data.workflow_runs[0];
            const status = latestRun ? latestRun.conclusion : 'unknown';
            
            console.log(`Latest CI status: ${status}`);
            
            // Badge colors
            const colors = {
              'success': 'brightgreen',
              'failure': 'red',
              'cancelled': 'yellow',
              'skipped': 'lightgrey',
              'unknown': 'lightgrey'
            };
            
            const color = colors[status] || 'lightgrey';
            const badgeUrl = `https://img.shields.io/badge/CI-${status}-${color}`;
            
            console.log(`Badge URL: ${badgeUrl}`);
            core.setOutput('badge_url', badgeUrl);
            core.setOutput('status', status);